### ISSUE TITLE
잘지내시죠?

### ISSUE THREAD

**Issue by nice7677** [heodokyung/portfolio-data-json#1]
잘지내시죠?

**Comment by heodokyung** [comment]
우와!! 오랜만입니다. !! 잘 지내나요?? 저는 뭐.. ㅋ 잘 지내는건지 모르겠네요~텔레 놔두고 ㅎㅎ 역시 깃헙 매니아아래 제 전화에요. 텔레로 친추해서 말 걸어주시면 좀 더 편하게 ㅎㅎ내가 진우맨 전번을 저장 못했네요. 진우맨 전전도 알려줘요 ㅎㅎ010-4744-0246
-------- 원본 이메일 --------발신: 진우 ***@***.***> 날짜: 22/11/4  오후 2:04  (GMT+09:00) 받은 사람: heodokyung/portfolio-data-json ***@***.***> 참조: Subscribed ***@***.***> 제목: [heodokyung/portfolio-data-json] 잘지내시죠? (Issue #1) 

잘지내시죠?

**Comment by heodokyung** [comment]
> 잘지내시죠?

우와!! 오랜만입니다. !! 잘 지내나요?? 저는 뭐.. ㅋ 잘 지내는건지 모르겠네요~텔레 놔두고 ㅎㅎ 역시 깃헙 매니아아래 제 전화에요. 텔레로 친추해서 말 걸어주시면 좀 더 편하게 ㅎㅎ내가 진우맨 전번을 저장 못했네요. 진우맨 전번 알려줘요~
